image: "quay.io/mocaccino/extra:latest"

package_dir: /gentoo

prelude:
- luet upgrade && luet install -y utils/tar utils/curl utils/xz
- mkdir /gentoo

steps:
# TODO: checksum
- curl -L http://distfiles.gentoo.org/releases/amd64/autobuilds/current-stage3-amd64/stage3-amd64-systemd-${STAGE_VERSION}.tar.xz | tar Jxp --xattrs --numeric-owner -C /gentoo

env:
- LUET_YES=true
- STAGE_VERSION={{ ( index .Values.labels "package.version" ) }}

# Add some common excludes
excludes:
- ^/etc/shadow
- ^/etc/os-release
- ^/etc/gshadow
- ^/etc/group
- ^/etc/hostname
- ^/etc/hosts
- ^/etc/machine-id
- ^/etc/fstab
- ^/etc/passwd
- ^/etc/machineid
- ^/sys
- ^/proc
